services:
  frontend:
    container_name: tubo-frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    volumes:
      - ./resources/config.edn:/app/resources/config.edn
    ports:
      - 8080:8080
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://localhost:3000
    restart: always
  backend:
    container_name: tubo-backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    volumes:
      - ./resources/config.edn:/app/resources/config.edn
    ports:
      - 3000:3000
    restart: always
  bg-helper:
    container_name: tubo-bg-helper
    build:
      context: .
      dockerfile: ./docker/bg-helper/Dockerfile
    volumes:
      - ./resources/config.edn:/app/resources/config.edn
    ports:
      - 3005:3005
    restart: always
