version: '3.7'

services:
  tubo:
    container_name: tubo
    hostname: tubo
    user: 65534:65534
    read_only: true
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '127.0.0.1:3080:3000'
    restart: always
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
