services:
  frontend:
    container_name: tubo-frontend
    build:
      context: .
      dockerfile: ./docker/frontend/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      - backend
    environment:
      - BACKEND_URL=http://localhost:3000
    restart: always
  backend:
    container_name: tubo-backend
    build:
      context: .
      dockerfile: ./docker/backend/Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_NAME=tubo
      - DB_USER=tubo
      - DB_PASSWORD=tubo
    restart: always
  db:
    container_name: tubo-db
    image: postgres:16-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=tubo
      - POSTGRES_USER=tubo
      - POSTGRES_PASSWORD=tubo
  bg-helper:
    container_name: tubo-bg-helper
    build:
      context: .
      dockerfile: ./docker/bg-helper/Dockerfile
    ports:
      - 3005:3005
    restart: always
