on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README*"

jobs:
  docker-publish:
    runs-on: auriga
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set registry
        run: echo "REGISTRY=${FORGEJO_SERVER_URL#http://}" >> $GITHUB_ENV

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        driver-opts: network=host

      - name: Login to Forgejo Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.FORGEJO_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          source: "."
          push: true
          set: |
            frontend.tags=${{ env.REGISTRY }}/migalmoreno/tubo-frontend:latest
            backend.tags=${{ env.REGISTRY }}/migalmoreno/tubo-backend:latest
            bg-helper.tags=${{ env.REGISTRY }}/migalmoreno/tubo-bg-helper:latest
            *.platform+=linux/amd64
            *.platform+=linux/arm64
            *.cache-from=type=registry,ref=${{ env.REGISTRY }}/migalmoreno/tubo-cache
            *.cache-to=type=registry,ref=${{ env.REGISTRY }}/migalmoreno/tubo-cache,mode=max
