DROP TABLE IF EXISTS users CASCADE;

--;;
DROP TABLE IF EXISTS channels CASCADE;

--;;
DROP TABLE IF EXISTS playlists CASCADE;

--;;
DROP TABLE IF EXISTS streams CASCADE;

--;;
DROP TABLE IF EXISTS playlist_streams;
