name: Publish Docker image

on:
  push:
    branches:
      - master
    paths-ignore:
      - "**/README"

jobs:
  docker-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push
        uses: docker/bake-action@v6
        with:
          push: true
          set: |
            backend.tags=migalmoreno/tubo-backend:latest
            bg-helper.tags=migalmoreno/tubo-bg-helper:latest
            *.platform+=linux/amd64
            *.platform+=linux/arm64
            *.cache-from=type=gha
            *.cache-to=type=gha,mode=max
